# Generated by Django 5.0.6 on 2024-05-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_application', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='')),
                ('utilisateur', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Serveur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('nb_processeur', models.IntegerField()),
                ('capacite_memoire', models.IntegerField()),
                ('capacite_stockage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=100)),
                ('date_lancement', models.DateField(blank=True)),
                ('espace_memoire_utilise', models.IntegerField()),
                ('memoire_vive_necessaire', models.IntegerField()),
                ('serveur_lancement', models.IntegerField()),
            ],
        ),
    ]
