# Generated by Django 5.0.6 on 2024-05-24 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAEserveur', '0002_tserveur_util'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='application',
            table='APPLICATION',
        ),
        migrations.AlterModelTable(
            name='serveur',
            table='SERVEUR',
        ),
        migrations.AlterModelTable(
            name='service',
            table='SERVICE',
        ),
        migrations.AlterModelTable(
            name='tserveur',
            table='TSERVEUR',
        ),
        migrations.AlterModelTable(
            name='util',
            table='UTIL',
        ),
    ]
