# Generated by Django 5.0.6 on 2024-06-12 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAEserveur', '0003_alter_application_table_alter_serveur_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serveur',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAEserveur.tserveur'),
        ),
    ]
