# Generated by Django 5.0.6 on 2024-06-12 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAEserveur', '0004_alter_serveur_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='serveur_lancement',
        ),
        migrations.AddField(
            model_name='service',
            name='serveur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='SAEserveur.serveur'),
        ),
    ]
